from ubuntu:16.04


RUN  apt-get update -y && \
     apt-get install -y python && \
     apt-get install -y python-pip && \
     apt-get install git  -y && \
     git clone https://github.com/umesh417/S3_Uploader.git &&\

WORKDIR  \S3_Uploader
 
RUN  pip install -r requirements.txt && \


ENV  APP_SETTINGS="config.DevelopmentConfig" && \
ENV  SECRET_KEY="your-random-secret-key" && \
ENV  S3_BUCKET="your-bucket-name"  && \
ENV  S3_KEY="your-aws-secret-key"  && \
ENV  S3_SECRET_ACCESS_KEY="your-aws-secret-access-key" && \
ENV  FLASK_APP=app.py


CMD [ python app.py ]

EXPOSE 5000